## Colab Prep

Execute the following code cells to whenever you open/restart the notebook in Google Colab.

In [ ]:
!pip install "polars[all]"

In [ ]:
!wget https://github.com/WSU-DataScience/dsci_325_module6_basic_data_management_in_python/raw/main/sample_data.zip

In [ ]:
!unzip ./sample_data.zip

# Select, Filter, and Mutate

In this lecture, we will look at three important actions used to process data frames.  While each framework uses different names for these function `polars` uses the following methods for each of the basic data verbs listed below.


1. SELECT is accomplished by dot-chaining into the dataframe `select` method. 
2. FILTER is accomplished by dot-chaining into either `filter` method.
3. MUTATE can be performed either as part of a `select`--as seen in SQL--or using the `with_columns` method.

## Example - Super Hero Information

To illustrate these data verbs, we will be using the `heroes_information.csv`, which contains information about various super heroes.

In [14]:
import polars as pl

In [15]:
heroes = pl.read_csv('./sample_data/heroes_information.csv')
heroes.head()

shape: (5, 11)
┌─────┬─────────────┬────────┬───────────┬─────┬─────────────────┬────────────┬───────────┬────────┐
│     ┆ name        ┆ Gender ┆ Eye color ┆ ... ┆ Publisher       ┆ Skin color ┆ Alignment ┆ Weight │
│ --- ┆ ---         ┆ ---    ┆ ---       ┆     ┆ ---             ┆ ---        ┆ ---       ┆ ---    │
│ i64 ┆ str         ┆ str    ┆ str       ┆     ┆ str             ┆ str        ┆ str       ┆ f64    │
╞═════╪═════════════╪════════╪═══════════╪═════╪═════════════════╪════════════╪═══════════╪════════╡
│ 0   ┆ A-Bomb      ┆ Male   ┆ yellow    ┆ ... ┆ Marvel Comics   ┆ -          ┆ good      ┆ 441.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1   ┆ Abe Sapien  ┆ Male   ┆ blue      ┆ ... ┆ Dark Horse      ┆ blue       ┆ good      ┆ 65.0   │
│     ┆             ┆        ┆           ┆     ┆ Comics          ┆            ┆           ┆        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ Abin Sur    ┆ Male   ┆ blue      ┆ ... ┆ DC Comics       ┆ red        ┆ good      ┆ 90.0   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 3   ┆ Abomination ┆ Male   ┆ green     ┆ ... ┆ Marvel Comics   ┆ -          ┆ bad       ┆ 441.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 4   ┆ Abraxas     ┆ Male   ┆ blue      ┆ ... ┆ Marvel Comics   ┆ -          ┆ bad       ┆ -99.0  │
└─────┴─────────────┴────────┴───────────┴─────┴─────────────────┴────────────┴───────────┴────────┘

In [4]:
heroes.dtypes

[polars.datatypes.Int64,
 polars.datatypes.Utf8,
 polars.datatypes.Utf8,
 polars.datatypes.Utf8,
 polars.datatypes.Utf8,
 polars.datatypes.Utf8,
 polars.datatypes.Float64,
 polars.datatypes.Utf8,
 polars.datatypes.Utf8,
 polars.datatypes.Utf8,
 polars.datatypes.Float64]

In [5]:
heroes.shape

(734, 11)

## Selecting Columns

The first verb, `select` 

* narrows the *columns*
* At the core of `SQL` statements

### How to select

<img src="https://github.com/WSU-DataScience/dsci_325_module6_basic_data_management_in_python/raw/main/img/dot_chain_select.png" width="800">

In [8]:
heroes.select(['Eye color', pl.col('name'), heroes['Gender']]).head()

shape: (5, 3)
┌───────────┬─────────────┬────────┐
│ Eye color ┆ name        ┆ Gender │
│ ---       ┆ ---         ┆ ---    │
│ str       ┆ str         ┆ str    │
╞═══════════╪═════════════╪════════╡
│ yellow    ┆ A-Bomb      ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ blue      ┆ Abe Sapien  ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ blue      ┆ Abin Sur    ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ green     ┆ Abomination ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ blue      ┆ Abraxas     ┆ Male   │
└───────────┴─────────────┴────────┘

### Spreading your code across many lines makes it more readable

<img src="https://github.com/WSU-DataScience/dsci_325_module6_basic_data_management_in_python/raw/main/img/spread_across_many_lines.png" width="600">

In [4]:
(heroes
 .select(['Eye color', 
          pl.col('name'),  
          heroes['Gender'],
         ])
 .head()
)

shape: (5, 3)
┌───────────┬─────────────┬────────┐
│ Eye color ┆ name        ┆ Gender │
│ ---       ┆ ---         ┆ ---    │
│ str       ┆ str         ┆ str    │
╞═══════════╪═════════════╪════════╡
│ yellow    ┆ A-Bomb      ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ blue      ┆ Abe Sapien  ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ blue      ┆ Abin Sur    ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ green     ┆ Abomination ┆ Male   │
├╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ blue      ┆ Abraxas     ┆ Male   │
└───────────┴─────────────┴────────┘

### Three ways to reference columns

<img src="https://github.com/WSU-DataScience/dsci_325_module6_basic_data_management_in_python/raw/main//img/reference_columns.png" width="500">

## Filtering Rows

<img src="https://github.com/WSU-DataScience/dsci_325_module6_basic_data_management_in_python/raw/main//img/filter.png">

The next verb, `filter` 

* filters the *rows*
* is related to the `SQL` `WHERE` clause

## How to filter

* dot-chain (`.`) into `filters` 
* First argument is a boolean expression
* Reference columns with `pl.col('column name')`

In [28]:
(heroes 
 .filter(pl.col('Gender') == 'Male') # With a column expression
 .head()
)

shape: (5, 11)
┌─────┬─────────────┬────────┬───────────┬─────┬─────────────────┬────────────┬───────────┬────────┐
│     ┆ name        ┆ Gender ┆ Eye color ┆ ... ┆ Publisher       ┆ Skin color ┆ Alignment ┆ Weight │
│ --- ┆ ---         ┆ ---    ┆ ---       ┆     ┆ ---             ┆ ---        ┆ ---       ┆ ---    │
│ i64 ┆ str         ┆ str    ┆ str       ┆     ┆ str             ┆ str        ┆ str       ┆ f64    │
╞═════╪═════════════╪════════╪═══════════╪═════╪═════════════════╪════════════╪═══════════╪════════╡
│ 0   ┆ A-Bomb      ┆ Male   ┆ yellow    ┆ ... ┆ Marvel Comics   ┆ -          ┆ good      ┆ 441.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1   ┆ Abe Sapien  ┆ Male   ┆ blue      ┆ ... ┆ Dark Horse      ┆ blue       ┆ good      ┆ 65.0   │
│     ┆             ┆        ┆           ┆     ┆ Comics          ┆            ┆           ┆        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ Abin Sur    ┆ Male   ┆ blue      ┆ ... ┆ DC Comics       ┆ red        ┆ good      ┆ 90.0   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 3   ┆ Abomination ┆ Male   ┆ green     ┆ ... ┆ Marvel Comics   ┆ -          ┆ bad       ┆ 441.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 4   ┆ Abraxas     ┆ Male   ┆ blue      ┆ ... ┆ Marvel Comics   ┆ -          ┆ bad       ┆ -99.0  │
└─────┴─────────────┴────────┴───────────┴─────┴─────────────────┴────────────┴───────────┴────────┘

### Column expressions a lazy

Column expressions are

* Lazy, waiting to process as long as possible.
* Allow us to reference newly created or changed columns 
* The safe/preferred method of referencing columns.

In [9]:
pl.col('Gender') == 'Male' # lazy Expr

### Getting columns from the dataframe is eager

When getting a column using `df[col_name]`

* Eager, getting the contents of the column when code is read
* Will throw an exception for newly created columns.
* Will use the original data and miss any changes made in the chain.
* Inefficient, as will read the whole original column and miss any filtering.

In [16]:
(heroes 
 .filter(heroes['Gender'] == 'Male') # Get column from dataframe
 .head()
)

shape: (5, 11)
┌─────┬─────────────┬────────┬───────────┬─────┬─────────────────┬────────────┬───────────┬────────┐
│     ┆ name        ┆ Gender ┆ Eye color ┆ ... ┆ Publisher       ┆ Skin color ┆ Alignment ┆ Weight │
│ --- ┆ ---         ┆ ---    ┆ ---       ┆     ┆ ---             ┆ ---        ┆ ---       ┆ ---    │
│ i64 ┆ str         ┆ str    ┆ str       ┆     ┆ str             ┆ str        ┆ str       ┆ f64    │
╞═════╪═════════════╪════════╪═══════════╪═════╪═════════════════╪════════════╪═══════════╪════════╡
│ 0   ┆ A-Bomb      ┆ Male   ┆ yellow    ┆ ... ┆ Marvel Comics   ┆ -          ┆ good      ┆ 441.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1   ┆ Abe Sapien  ┆ Male   ┆ blue      ┆ ... ┆ Dark Horse      ┆ blue       ┆ good      ┆ 65.0   │
│     ┆             ┆        ┆           ┆     ┆ Comics          ┆            ┆           ┆        │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2   ┆ Abin Sur    ┆ Male   ┆ blue      ┆ ... ┆ DC Comics       ┆ red        ┆ good      ┆ 90.0   │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 3   ┆ Abomination ┆ Male   ┆ green     ┆ ... ┆ Marvel Comics   ┆ -          ┆ bad       ┆ 441.0  │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 4   ┆ Abraxas     ┆ Male   ┆ blue      ┆ ... ┆ Marvel Comics   ┆ -          ┆ bad       ┆ -99.0  │
└─────┴─────────────┴────────┴───────────┴─────┴─────────────────┴────────────┴───────────┴────────┘

In [18]:
heroes['Gender'] == 'Male' # Eager, creating a Boolean series ASAP

shape: (734,)
Series: 'Gender' [bool]
[
	true
	true
	true
	true
	true
	true
	true
	true
	false
	true
	true
	true
	...
	true
	false
	false
	true
	false
	true
	true
	true
	false
	true
	true
	false
	true
]

## Chaining Data Verbs

* Processing df $\rightarrow$ chaining together many data verbs
* Accomplished through dot-chains

### Example 1 - `select` + `filter`

In [11]:
(heroes 
 .filter(pl.col('Gender') == 'Male') 
 .select(['name', 'Gender', 'Weight'])
 .head()
)

shape: (5, 3)
┌─────────────┬────────┬────────┐
│ name        ┆ Gender ┆ Weight │
│ ---         ┆ ---    ┆ ---    │
│ str         ┆ str    ┆ f64    │
╞═════════════╪════════╪════════╡
│ A-Bomb      ┆ Male   ┆ 441.0  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Abe Sapien  ┆ Male   ┆ 65.0   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Abin Sur    ┆ Male   ┆ 90.0   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Abomination ┆ Male   ┆ 441.0  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Abraxas     ┆ Male   ┆ -99.0  │
└─────────────┴────────┴────────┘

### Example 2 - `filter` + `filter`

Note that chaining `filter`s is an `and` operation.

In [12]:
(heroes
.select(['name', 'Gender', 'Weight'])
.filter(pl.col('Gender') == 'Male')
.filter(pl.col('Weight') > 0)
.head()
)

shape: (5, 3)
┌───────────────┬────────┬────────┐
│ name          ┆ Gender ┆ Weight │
│ ---           ┆ ---    ┆ ---    │
│ str           ┆ str    ┆ f64    │
╞═══════════════╪════════╪════════╡
│ A-Bomb        ┆ Male   ┆ 441.0  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Abe Sapien    ┆ Male   ┆ 65.0   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Abin Sur      ┆ Male   ┆ 90.0   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Abomination   ┆ Male   ┆ 441.0  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ Absorbing Man ┆ Male   ┆ 122.0  │
└───────────────┴────────┴────────┘

## <font color="red"> Exercise 6.2.1: Blue-eyed Heroes </font>

Create a query that

1. Selects the name, Gender, and Eye Color columns
2. Filters on eye_color == 'blue'

In [12]:
# Your code here

## Constructing New Columns

The third verb, `mutate` 

* Creates new columns
* Changes existing columns

### Method 1 - Inside `select`

*  dot-chain (`.`) into `select`
* Include one or more mutates in the `list` of expressions.
* Name the new column using `alias`

#### Example - Converting Weight from pounds to kilograms inside `select`

In [19]:
(heroes 
 .select(['name', 
          'Gender', 
          'Weight',
          (pl.col('Weight')/2.2046).alias('Weight_kg'),
         ]) 
 .head()
)

shape: (5, 4)
┌─────────────┬────────┬────────┬────────────┐
│ name        ┆ Gender ┆ Weight ┆ Weight_kg  │
│ ---         ┆ ---    ┆ ---    ┆ ---        │
│ str         ┆ str    ┆ f64    ┆ f64        │
╞═════════════╪════════╪════════╪════════════╡
│ A-Bomb      ┆ Male   ┆ 441.0  ┆ 200.036288 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abe Sapien  ┆ Male   ┆ 65.0   ┆ 29.483807  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abin Sur    ┆ Male   ┆ 90.0   ┆ 40.823732  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abomination ┆ Male   ┆ 441.0  ┆ 200.036288 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abraxas     ┆ Male   ┆ -99.0  ┆ -44.906105 │
└─────────────┴────────┴────────┴────────────┘

### Method 2 - Mutate using `with_columns`

* dot-chain (`.`) into `with_columns`
* First argument is a `list` of transformational expressions
* Reference columns with `pl.col('column_name')` or `df['column name']`
* Name the new column using `alias`

In [21]:
(heroes 
 .select(['name', 
          'Gender', 
          'Weight'
         ]) 
 .with_columns([(pl.col('Weight')/2.2046).alias('Weight_kg'),
                (pl.col('Weight')/2.2046*1000).alias('Weight_g'),
               ]) 
 .head()
)

shape: (5, 5)
┌─────────────┬────────┬────────┬────────────┬───────────────┐
│ name        ┆ Gender ┆ Weight ┆ Weight_kg  ┆ Weight_g      │
│ ---         ┆ ---    ┆ ---    ┆ ---        ┆ ---           │
│ str         ┆ str    ┆ f64    ┆ f64        ┆ f64           │
╞═════════════╪════════╪════════╪════════════╪═══════════════╡
│ A-Bomb      ┆ Male   ┆ 441.0  ┆ 200.036288 ┆ 200036.287762 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abe Sapien  ┆ Male   ┆ 65.0   ┆ 29.483807  ┆ 29483.806586  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abin Sur    ┆ Male   ┆ 90.0   ┆ 40.823732  ┆ 40823.732196  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abomination ┆ Male   ┆ 441.0  ┆ 200.036288 ┆ 200036.287762 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abraxas     ┆ Male   ┆ -99.0  ┆ -44.906105 ┆ -44906.105416 │
└─────────────┴────────┴────────┴────────────┴───────────────┘

### Making this more readable with keyword arguments

* Use `new_var = col_expr`.
* Removes the need for `alias`
* `new_var` must be a proper Python name
    * Only letter, numbers, or `_`.
* Experimental, requires Config

In [23]:
pl.Config.with_columns_kwargs = True

(heroes 
 .select(['name', 
          'Gender', 
          'Weight'
         ]) 
 .with_columns(Weight_kg = pl.col('Weight')/2.2046,
               Weight_g =  pl.col('Weight')/2.2046*1000,
               ) 
 .head()
)

shape: (5, 5)
┌─────────────┬────────┬────────┬────────────┬───────────────┐
│ name        ┆ Gender ┆ Weight ┆ Weight_kg  ┆ Weight_g      │
│ ---         ┆ ---    ┆ ---    ┆ ---        ┆ ---           │
│ str         ┆ str    ┆ f64    ┆ f64        ┆ f64           │
╞═════════════╪════════╪════════╪════════════╪═══════════════╡
│ A-Bomb      ┆ Male   ┆ 441.0  ┆ 200.036288 ┆ 200036.287762 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abe Sapien  ┆ Male   ┆ 65.0   ┆ 29.483807  ┆ 29483.806586  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abin Sur    ┆ Male   ┆ 90.0   ┆ 40.823732  ┆ 40823.732196  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abomination ┆ Male   ┆ 441.0  ┆ 200.036288 ┆ 200036.287762 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abraxas     ┆ Male   ┆ -99.0  ┆ -44.906105 ┆ -44906.105416 │
└─────────────┴────────┴────────┴────────────┴───────────────┘

## Referencing a new column is tricky!

If we reference a new column in the same `with_columns` or `select`, we get an exception.

In [26]:
pl.Config.with_columns_kwargs = True

(heroes 
 .select(['name', 
          'Gender', 
          'Weight'
         ]) 
 .with_columns(Weight_kg = pl.col('Weight')/2.2046,
               Weight_g =  pl.col('Weight_kg')*1000) # References new column ==> CRASH!
 .filter(pl.col('Weight_kg') < 100) 
 .head()
)

NotFoundError: Weight_kg

### How to read a Python exception

<img src="https://github.com/WSU-DataScience/dsci_325_module6_basic_data_management_in_python/raw/main//img/read_an_exception.png" width="800">

## Referencing a new column

* Newly created columns can't be referenced in the same `select` or `with_columns`.
* Use `pl.col('new_column')` to reference in later method calls.
* Add additional `with_columns` to use in new expressions.

In [27]:
pl.Config.with_columns_kwargs = True

(heroes 
 .select(['name', 
          'Gender', 
          'Weight'
         ]) 
 .with_columns(Weight_kg = pl.col('Weight')/2.2046)
 .with_columns(Weight_g =  pl.col('Weight_kg')*1000) # Can reference in new call
 .filter(pl.col('Weight_kg') < 100) 
 .head()
)

shape: (5, 5)
┌───────────────┬────────┬────────┬────────────┬───────────────┐
│ name          ┆ Gender ┆ Weight ┆ Weight_kg  ┆ Weight_g      │
│ ---           ┆ ---    ┆ ---    ┆ ---        ┆ ---           │
│ str           ┆ str    ┆ f64    ┆ f64        ┆ f64           │
╞═══════════════╪════════╪════════╪════════════╪═══════════════╡
│ Abe Sapien    ┆ Male   ┆ 65.0   ┆ 29.483807  ┆ 29483.806586  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abin Sur      ┆ Male   ┆ 90.0   ┆ 40.823732  ┆ 40823.732196  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Abraxas       ┆ Male   ┆ -99.0  ┆ -44.906105 ┆ -44906.105416 │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Absorbing Man ┆ Male   ┆ 122.0  ┆ 55.338837  ┆ 55338.836977  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Adam Monroe   ┆ Male   ┆ -99.0  ┆ -44.906105 ┆ -44906.105416 │
└───────────────┴────────┴────────┴────────────┴───────────────┘

## <font color="red"> Exercise 6.2.2: Tall Heroes </font>

Create a query that

1. Selects the name, Gender, and Height columns
2. Compute the height in inches.
    * Check [here](https://www.kaggle.com/claudiodavi/superhero-set) to determine the current units.
3. Filters on height_in > 72

In [ ]:
# Your code here